[package]
name = "wm-cli"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "glazewm-cli"
path = "src/main.rs"

[build-dependencies]
tauri-winres = { workspace = true }

[dependencies]
anyhow = { workspace = true }
futures-util = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
uuid = { workspace = true }
wm-common = { path = "../wm-common" }
wm-ipc-client = { path = "../wm-ipc-client" }
