name: Package

on:
  workflow_call:
  workflow_dispatch:

jobs:
  next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@3c2d88ce0390012bac0b8383059a0b67d2594dc1

  package:
    needs: [next-version]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
        with:
          toolchain: nightly
          targets: x86_64-pc-windows-msvc,aarch64-pc-windows-msvc

      - uses: swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3

      - name: Install WiX and its extensions
        run: |
          dotnet tool install --global wix --version 5.0.0
          wix extension add WixToolset.UI.wixext/5 WixToolset.Util.wixext/5 WixToolset.BootstrapperApplications.wixext/5

      - name: Install AzureSignTool
        run: |
          dotnet tool install --global AzureSignTool --version 5.0.0

      - name: Run packaging script
        env:
          AZ_VAULT_URL: ${{ secrets.AZ_VAULT_URL }}
          AZ_CERT_NAME: ${{ secrets.AZ_CERT_NAME }}
          AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
          AZ_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
          AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
          RFC3161_TIMESTAMP_URL: ${{ vars.RFC3161_TIMESTAMP_URL }}
        run: |
          ./resources/scripts/package.ps1 -VersionNumber ${{ needs.next-version.outputs.new-release-version || '3.1.0' }}

      - uses: actions/upload-artifact@v4
        with:
          name: installers
          if-no-files-found: error
          path: out/installer-*
